#!/usr/bin/env python3
"""WID4 celestial map generator.

Reads celestial_map.json (same directory unless --manifest is given) and emits a
celestialObjects XML matching WarpDrive.xsd schema version 3.

Design rules:
- Bodies sit on rings with a FIXED slot count: adding a body to a free slot never
  moves existing bodies. Never renumber a slot that shipped to players.
- Dimension ids come from the mods' configs: verify before adding entries.
- Validation mirrors CelestialObjectManager.rebuildAndValidate: the script fails,
  the server doesn't.

Usage:
  python gen_celestial_map.py                       # writes the fork resource
  python gen_celestial_map.py --out <path> [...]    # writes to explicit target(s)
  python gen_celestial_map.py --check               # validate only
"""

import argparse
import json
import math
import os
import sys

DEFAULT_OUTPUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "src", "main", "resources", "config",
    "celestialObjects-Galacticraft+ExtraPlanets.xml")

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<worldGeneration version="3"\n'
    '\t\t\t\t xmlns="http://warpdrive.lemadec.org"\n'
    '\t\t\t\t xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
    '\t\t\t\t xsi:schemaLocation="http://warpdrive.lemadec.org WarpDrive.xsd"\n'
    '\t\t\t\t mods="{mods}">\n'
    '\n'
    '\t<!-- WID4 celestial map - generated by tools/gen_celestial_map.py. Do not hand-edit.\n'
    '\t     Regenerate: python tools/gen_celestial_map.py  (see tools/README.md) -->\n')

FOOTER = '</worldGeneration>\n'


def die(message):
    sys.stderr.write("ERROR: %s\n" % message)
    sys.exit(1)


def xml_escape(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def fnum(value):
    return ("%.2f" % value)


class Body(object):
    """Resolved celestial object with absolute parent-space coordinates."""

    def __init__(self, node, parent_center, ring_layout, depth):
        self.id = node["id"]
        self.name = node.get("name")
        self.description = node.get("description")
        self.nbt = node.get("nbt")
        self.mods = node.get("mods")
        self.size = int(node["size"])
        self.radius = self.size // 2
        self.dim = node.get("dim")
        self.breathable = bool(node.get("breathable", False))
        self.hyperspace = bool(node.get("hyperspace", False))
        self.gravity = node.get("gravity", "normal")
        self.provider = node.get("provider")
        self.generate = node.get("generate", [])
        self.skybox = node.get("skybox")
        self.renders = node.get("renders", [])
        self.depth = depth

        if "center" in node:
            self.x = parent_center[0] + int(node["center"][0])
            self.z = parent_center[1] + int(node["center"][1])
        elif "ring" in node and "slot" in node:
            if ring_layout is None:
                die("body %s uses ring/slot but its parent declares no rings" % self.id)
            radii, slot_counts = ring_layout
            ring = int(node["ring"])
            slot = int(node["slot"])
            if ring >= len(radii):
                die("body %s ring %d exceeds declared rings" % (self.id, ring))
            if slot >= slot_counts[ring]:
                die("body %s slot %d exceeds ring %d capacity %d"
                    % (self.id, slot, ring, slot_counts[ring]))
            angle = 2.0 * math.pi * slot / slot_counts[ring]
            self.x = parent_center[0] + int(round(radii[ring] * math.cos(angle)))
            self.z = parent_center[1] + int(round(radii[ring] * math.sin(angle)))
        elif "angle" in node and "radius" in node:
            angle = math.radians(float(node["angle"]))
            self.x = parent_center[0] + int(round(float(node["radius"]) * math.cos(angle)))
            self.z = parent_center[1] + int(round(float(node["radius"]) * math.sin(angle)))
        else:
            die("body %s needs center, ring+slot or angle+radius" % self.id)

        child_rings = None
        if "rings" in node:
            child_rings = ([int(r) for r in node["rings"]],
                           [int(c) for c in node["slots_per_ring"]])
        # a child's <parent><center> is expressed in this object's DIMENSION coordinate
        # space, which is centered on (0,0) by convention; children of a virtual (render
        # only) object live in the same space as the virtual object itself
        base = (0, 0) if self.dim is not None else (self.x, self.z)
        self.children = [Body(child, base, child_rings, depth + 1)
                         for child in node.get("children", [])]

    def is_virtual(self):
        return self.dim is None

    def area(self):
        return (self.x - self.radius, self.z - self.radius,
                self.x + self.radius, self.z + self.radius)

    def emit(self, out, indent):
        pad = "\t" * indent
        mods = (' mods="%s"' % xml_escape(self.mods)) if self.mods else ""
        out.append('%s<celestialObject id="%s"%s>' % (pad, xml_escape(self.id), mods))
        if self.depth > 0:
            # the root (hyperspace) has no parent element: its absence marks the hyperspace root
            out.append('%s\t<parent><center x="%d" z="%d" /></parent>' % (pad, self.x, self.z))
        out.append('%s\t<size x="%d" z="%d" />' % (pad, self.size, self.size))
        if self.name:
            out.append('%s\t<name>%s</name>' % (pad, xml_escape(self.name)))
        if self.description:
            out.append('%s\t<description>%s</description>' % (pad, xml_escape(self.description)))
        if self.nbt:
            out.append('%s\t<nbt>%s</nbt>' % (pad, xml_escape(self.nbt)))
        if self.dim is not None:
            attrs = 'id="%d" isBreathable="%s"' % (self.dim, "true" if self.breathable else "false")
            if self.hyperspace:
                attrs += ' isHyperspace="true"'
            attrs += ' gravity="%s"' % self.gravity
            if self.provider or self.generate:
                out.append('%s\t<dimension %s>' % (pad, attrs))
                out.append('%s\t\t<center x="0" z="0" />' % pad)
                if self.provider:
                    out.append('%s\t\t<provider type="%s" />' % (pad, self.provider))
                for generate in self.generate:
                    extra = "".join(' %s="%s"' % (key, generate[key])
                                    for key in sorted(generate) if key != "group")
                    out.append('%s\t\t<generate group="%s"%s />' % (pad, generate["group"], extra))
                out.append('%s\t</dimension>' % pad)
            else:
                out.append('%s\t<dimension %s><center x="0" z="0" /></dimension>' % (pad, attrs))
        if self.skybox:
            emit_skybox(out, pad + "\t", self.skybox)
        for render in self.renders:
            emit_render(out, pad + "\t", render)
        for child in self.children:
            child.emit(out, indent + 1)
        out.append('%s</celestialObject>' % pad)


def emit_skybox(out, pad, skybox):
    out.append('%s<skybox>' % pad)
    if "backgroundColor" in skybox:
        red, green, blue = skybox["backgroundColor"]
        out.append('%s\t<backgroundColor red="%s" green="%s" blue="%s" />'
                   % (pad, fnum(red), fnum(green), fnum(blue)))
    for tag in ("boxBrightness", "starBrightnessBase", "starBrightnessVanilla", "celestialObjectOpacity"):
        if tag in skybox:
            out.append('%s\t<%s>%s</%s>' % (pad, tag, skybox[tag], tag))
    if "fogColor" in skybox:
        red, green, blue = skybox["fogColor"]
        out.append('%s\t<fogColor red="%s" green="%s" blue="%s" />'
                   % (pad, fnum(red), fnum(green), fnum(blue)))
    if "fogFactor" in skybox:
        red, green, blue = skybox["fogFactor"]
        out.append('%s\t<fogFactor red="%s" green="%s" blue="%s" />'
                   % (pad, fnum(red), fnum(green), fnum(blue)))
    out.append('%s</skybox>' % pad)


def emit_render(out, pad, render):
    red, green, blue, alpha = render[0], render[1], render[2], render[3]
    extra = ""
    if len(render) > 4 and render[4]:
        extra = ' texture="%s"' % render[4]
        if len(render) > 5 and render[5]:
            extra += ' periodU="%s"' % render[5]
    out.append('%s<render red="%s" green="%s" blue="%s" alpha="%s"%s />'
               % (pad, fnum(red), fnum(green), fnum(blue), fnum(alpha), extra))


def collect(body, flat):
    flat.append(body)
    for child in body.children:
        collect(child, flat)


def validate(root):
    flat = []
    collect(root, flat)
    errors = []

    ids = {}
    dims = {}
    for body in flat:
        if body.id in ids:
            errors.append("duplicate id %s" % body.id)
        ids[body.id] = body
        if body.dim is not None:
            if body.dim in dims:
                errors.append("dimension %d used by both %s and %s"
                              % (body.dim, dims[body.dim].id, body.id))
            dims[body.dim] = body

    def check_children(parent):
        for child in parent.children:
            # containment within the parent's world border (parent-space coordinates)
            if parent.dim is not None:
                x_min, z_min, x_max, z_max = child.area()
                # child parent-space coordinates are absolute in the parent dimension
                if (x_min < -parent.radius or z_min < -parent.radius
                        or x_max > parent.radius or z_max > parent.radius):
                    # parent world border is centered on its dimension center (0,0 by convention)
                    errors.append("%s area (%d..%d, %d..%d) exceeds parent %s border radius %d"
                                  % (child.id, x_min, x_max, z_min, z_max, parent.id, parent.radius))
            for sibling in parent.children:
                if sibling is child or sibling.is_virtual() or child.is_virtual():
                    continue
                ax = child.area()
                bx = sibling.area()
                if ax[0] < bx[2] and ax[2] > bx[0] and ax[1] < bx[3] and ax[3] > bx[1]:
                    key = tuple(sorted((child.id, sibling.id)))
                    message = "overlap between %s and %s in %s" % (key[0], key[1], parent.id)
                    if message not in errors:
                        errors.append(message)
            if abs(child.x) + child.radius >= 30000000 or abs(child.z) + child.radius >= 30000000:
                errors.append("%s exceeds the +/-30M game border" % child.id)
            check_children(child)

    check_children(root)
    return errors


def main():
    parser = argparse.ArgumentParser(description="Generate the WID4 celestial map XML")
    parser.add_argument("--manifest", default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                           "celestial_map.json"))
    parser.add_argument("--out", action="append", default=None,
                        help="output path(s); default is the fork resource XML")
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = parser.parse_args()

    with open(args.manifest, "r", encoding="utf-8") as handle:
        manifest = json.load(handle)

    root = Body(manifest["hyperspace"], (0, 0), None, 0)

    errors = validate(root)
    if errors:
        for error in errors:
            sys.stderr.write("VALIDATION: %s\n" % error)
        die("%d validation error(s), nothing written" % len(errors))

    if args.check:
        print("Manifest is valid.")
        return

    out = []
    root.emit(out, 1)
    content = (HEADER.format(mods=manifest.get("mods", "galacticraftcore"))
               + "\n".join(out) + "\n\n" + FOOTER)

    targets = args.out if args.out else [os.path.normpath(DEFAULT_OUTPUT)]
    for target in targets:
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        print("Wrote %s" % target)


if __name__ == "__main__":
    main()
